# example values
server:
  port: 8080

spring:
  #session:
    #jdbc:
      #initialize-schema: always
  flyway:
    create-schemas: true
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



    #properties:
      #hibernate:
       # dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.lenta.ru
      name: Лента.ру
    #- url: https://www.skillbox.ru
    #  name: Skillbox
    #- url: https://www.playback.ru
      #name: PlayBack.Ru
    #- url: http://redmine-reports.soctech.loc
      #name: Soctech.loc
  userAgent: Mozilla/5.0 (Windows NT 6.1; rv:98.0) Gecko/20100101 Firefox/98.0
  referrer: http://www.google.com