server:
  port: 8080

spring:
  flyway:
    create-schemas: true
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    #- url: https://www.lenta.ru
      #name: Лента.ру
    #- url: https://www.skillbox.ru
      #name: Skillbox
    #- url: https://www.playback.ru
      #name: PlayBack.Ru
    #- url: http://redmine-reports.soctech.loc
      #name: Soctech.loc
search:
  engine:
    user:
      agent: ${USER_AGENT}
      referrer: ${REFERRER}
    db:
      url: ${DB_URL}
      username: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
